### ISSUE TITLE
Can not find HttpDialog(host, port) mentioned in documentation

### ISSUE THREAD

**Issue by C-h-e-r-r-y** [spray/spray-can#26]
There is a code block `HttpDialog(host = "img.example.com", port = 8888)` on main [page](https://github.com/spray/spray-can#httpdialog-dsl). But I can not find such constructor or apply method in the code only: 

```
apply(transport: ActorRef)
apply(connect: Http.Connect)
apply()
```

Is it supported or not?

**Comment by jrudolph** [comment]
This repository has long been outdated. See, http://spray.io and the https://github.com/spray/spray for recent information
