### ISSUE TITLE
Your documentation website at spray.io is down

### ISSUE THREAD

**Issue by philliptaylorpro** [spray/spray-can#29]
Just letting you know. Even though this is a super old technology, access to the documentation is still useful for the people who adopted it.

**Comment by sirthias** [comment]
Ah, sorry, will get it back up shortly.
Thank you for the heads-up!

**Comment by sirthias** [comment]
And back up it is!
Thanks again!

**Comment by philliptaylorpro** [comment]
Yeah it's up. Thank you @sirthias
